services:
  nginx:
    image: nginx:alpine
    container_name: krea_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl:ro
    restart: unless-stopped
    depends_on:
      - n8n
      - qdrant
      - ollama
      - portainer
      - filebrowser

  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres_db
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_password
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.kreacity.cloud
      GENERIC_TIMEZONE: UTC
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
      N8N_TEMPLATES_ENABLED: false
      N8N_PERSONALIZATION_ENABLED: false
      N8N_ANONYMIZE_DATA_COLLECTION: true
      N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN: true
      N8N_DISABLE_PRODUCTION_MAIN_PROCESS: true
      N8N_HIDE_USAGE_PAGE: true
      N8N_DIAGNOSTICS_CONFIG_ENABLED: false
      EXECUTIONS_DATA_PRUNE: true
      EXECUTIONS_DATA_MAX_AGE: 1
      N8N_METRICS: false
    expose:
      - "5678"
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    expose:
      - "6333"
      - "6334"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    expose:
      - "11434"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0:11434
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    expose:
      - "80"
    ports:
      - "8081:80"
    volumes:
      - ./:/srv/platform
      - /var/lib/docker/volumes:/srv/volumes:ro
      - filebrowser_data:/database
      - filebrowser_config:/config
    environment:
      FB_DATABASE: /database/filebrowser.db
      FB_CONFIG: /config/settings.json
    restart: unless-stopped
    command: --noauth

volumes:
  postgres_data:
  n8n_data:
  qdrant_data:
  ollama_data:
  portainer_data:
  filebrowser_data:
  filebrowser_config:
