# /configs/authelia/configuration.yml - Version Statique et Valide

server:
  address: tcp://0.0.0.0:9091

session:
  secret: ${AUTHELIA_SESSION_SECRET}
  name: kreavps_session
  cookies:
    - domain: .${DOMAIN} # Le point est important pour inclure les sous-domaines
      default_redirection_url: https://chat.${DOMAIN}

jwt_secret: ${AUTHELIA_JWT_SECRET}

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: "auth.${DOMAIN}"
      policy: bypass
    - domain:
      - "n8n.${DOMAIN}"
      - "chat.${DOMAIN}"
      - "db.${DOMAIN}"
      - "docker.${DOMAIN}"
      - "traefik.${DOMAIN}"
      policy: one_factor

notifier:
  filesystem:
    filename: /tmp/notifications.log